export const CONTRACT_ADDRESS = "0x23De63242412e53158985F1379688C30B8CEF5B3";
export const CONTRACT_ADDRESS_ABI = [
  {
    inputs: [
      { name: "_owner", internalType: "address", type: "address" },
      { name: "_operator", internalType: "address", type: "address" },
    ],
    stateMutability: "nonpayable",
    type: "constructor",
  },
  {
    inputs: [
      {
        indexed: false,
        name: "amount",
        internalType: "uint256",
        type: "uint256",
      },
      {
        indexed: false,
        name: "time",
        internalType: "uint256",
        type: "uint256",
      },
      {
        indexed: false,
        name: "user",
        internalType: "address",
        type: "address",
      },
      {
        indexed: false,
        name: "userReferal",
        internalType: "address",
        type: "address",
      },
      {
        indexed: false,
        name: "virtualTokenUsed",
        internalType: "uint256",
        type: "uint256",
      },
      {
        indexed: false,
        name: "split",
        internalType: "uint256",
        type: "uint256",
      },
      {
        indexed: false,
        name: "level",
        internalType: "uint256",
        type: "uint256",
      },
    ],
    name: "UserDepositDetail",
    anonymous: false,
    type: "event",
  },
  {
    inputs: [
      {
        indexed: false,
        name: "amount",
        internalType: "uint256",
        type: "uint256",
      },
      {
        indexed: false,
        name: "user",
        internalType: "address",
        type: "address",
      },
      {
        indexed: false,
        name: "incomeType",
        internalType: "string",
        type: "string",
      },
      {
        indexed: false,
        name: "time",
        internalType: "uint256",
        type: "uint256",
      },
    ],
    name: "centraliseIncomeUpdate",
    anonymous: false,
    type: "event",
  },
  {
    inputs: [
      {
        indexed: false,
        name: "amount",
        internalType: "uint256",
        type: "uint256",
      },
      {
        indexed: false,
        name: "time",
        internalType: "uint256",
        type: "uint256",
      },
      {
        indexed: false,
        name: "user",
        internalType: "address",
        type: "address",
      },
      {
        indexed: false,
        name: "userReferal",
        internalType: "address",
        type: "address",
      },
    ],
    name: "depositForFriend",
    anonymous: false,
    type: "event",
  },
  {
    inputs: [
      {
        indexed: false,
        name: "user",
        internalType: "address",
        type: "address",
      },
      {
        indexed: false,
        name: "recivedFrom",
        internalType: "address",
        type: "address",
      },
      {
        indexed: false,
        name: "amount",
        internalType: "uint256",
        type: "uint256",
      },
      {
        indexed: false,
        name: "time",
        internalType: "uint256",
        type: "uint256",
      },
      {
        indexed: false,
        name: "level",
        internalType: "uint256",
        type: "uint256",
      },
    ],
    name: "levelVirtualTokenDistribution",
    anonymous: false,
    type: "event",
  },
  {
    inputs: [
      {
        indexed: false,
        name: "amount",
        internalType: "uint256",
        type: "uint256",
      },
      {
        indexed: false,
        name: "time",
        internalType: "uint256",
        type: "uint256",
      },
      {
        indexed: false,
        name: "user",
        internalType: "address",
        type: "address",
      },
      {
        indexed: false,
        name: "userReferal",
        internalType: "address",
        type: "address",
      },
    ],
    name: "reTopup",
    anonymous: false,
    type: "event",
  },
  {
    inputs: [
      {
        indexed: false,
        name: "user",
        internalType: "address",
        type: "address",
      },
      {
        indexed: false,
        name: "userReferal",
        internalType: "address",
        type: "address",
      },
      {
        indexed: false,
        name: "time",
        internalType: "uint256",
        type: "uint256",
      },
    ],
    name: "registerDetail",
    anonymous: false,
    type: "event",
  },
  {
    inputs: [
      {
        indexed: false,
        name: "time",
        internalType: "uint256",
        type: "uint256",
      },
      {
        indexed: false,
        name: "user",
        internalType: "address",
        type: "address",
      },
    ],
    name: "user2xDetail",
    anonymous: false,
    type: "event",
  },
  {
    inputs: [
      {
        indexed: false,
        name: "time",
        internalType: "uint256",
        type: "uint256",
      },
      {
        indexed: false,
        name: "user",
        internalType: "address",
        type: "address",
      },
    ],
    name: "user4xDetail",
    anonymous: false,
    type: "event",
  },
  {
    inputs: [
      {
        indexed: false,
        name: "time",
        internalType: "uint256",
        type: "uint256",
      },
      {
        indexed: false,
        name: "user",
        internalType: "address",
        type: "address",
      },
    ],
    name: "userStandardRoiDetail",
    anonymous: false,
    type: "event",
  },
  {
    inputs: [
      {
        indexed: false,
        name: "amount",
        internalType: "uint256",
        type: "uint256",
      },
      {
        indexed: false,
        name: "user",
        internalType: "address",
        type: "address",
      },
      {
        indexed: false,
        name: "time",
        internalType: "uint256",
        type: "uint256",
      },
    ],
    name: "userVirtualTokenClaimDetailOfRegistration",
    anonymous: false,
    type: "event",
  },
  {
    inputs: [
      {
        indexed: false,
        name: "retopup",
        internalType: "uint256",
        type: "uint256",
      },
      {
        indexed: false,
        name: "split",
        internalType: "uint256",
        type: "uint256",
      },
      {
        indexed: false,
        name: "wallet",
        internalType: "uint256",
        type: "uint256",
      },
      {
        indexed: false,
        name: "time",
        internalType: "uint256",
        type: "uint256",
      },
      {
        indexed: false,
        name: "user",
        internalType: "address",
        type: "address",
      },
    ],
    name: "withdrawBalanceEvent",
    anonymous: false,
    type: "event",
  },
  {
    outputs: [
      { name: "", internalType: "uint256", type: "uint256" },
      { name: "", internalType: "uint256", type: "uint256" },
      { name: "", internalType: "uint256", type: "uint256" },
    ],
    inputs: [{ name: "user", internalType: "address", type: "address" }],
    name: "ReturnWithdrawBalance",
    stateMutability: "view",
    type: "function",
  },
  {
    outputs: [{ name: "", internalType: "uint256", type: "uint256" }],
    inputs: [{ name: "", internalType: "address", type: "address" }],
    name: "StartingTime",
    stateMutability: "view",
    type: "function",
  },
  {
    outputs: [
      { name: "userID", internalType: "uint256", type: "uint256" },
      { name: "userReferalAddress", internalType: "address", type: "address" },
      { name: "totalDirects", internalType: "uint256", type: "uint256" },
      { name: "RegistrationTime", internalType: "uint256", type: "uint256" },
      { name: "firstDeposit", internalType: "uint256", type: "uint256" },
      { name: "myTotalbussiness", internalType: "uint256", type: "uint256" },
      { name: "total4XAmount", internalType: "uint256", type: "uint256" },
      { name: "totalOrganicAmount", internalType: "uint256", type: "uint256" },
      { name: "mydirectBussiness", internalType: "uint256", type: "uint256" },
      { name: "latestRank", internalType: "uint256", type: "uint256" },
      {
        name: "TotalLevelVirtualToken",
        internalType: "uint256",
        type: "uint256",
      },
      {
        name: "TotalLevelVirtualTokenAvailable",
        internalType: "uint256",
        type: "uint256",
      },
      {
        name: "TotalLevelVirtualTokenUsed",
        internalType: "uint256",
        type: "uint256",
      },
    ],
    inputs: [{ name: "", internalType: "address", type: "address" }],
    name: "UserDetail",
    stateMutability: "view",
    type: "function",
  },
  {
    outputs: [{ name: "", internalType: "uint256", type: "uint256" }],
    inputs: [{ name: "", internalType: "address", type: "address" }],
    name: "addressToId",
    stateMutability: "view",
    type: "function",
  },
  {
    outputs: [],
    inputs: [
      { name: "amount", internalType: "uint256", type: "uint256" },
      { name: "userAddr", internalType: "address", type: "address" },
    ],
    name: "deposit",
    stateMutability: "payable",
    type: "function",
  },
  {
    outputs: [{ name: "", internalType: "uint256", type: "uint256" }],
    inputs: [],
    name: "idProvider",
    stateMutability: "view",
    type: "function",
  },
  {
    outputs: [{ name: "", internalType: "address", type: "address" }],
    inputs: [{ name: "", internalType: "uint256", type: "uint256" }],
    name: "idToAddress",
    stateMutability: "view",
    type: "function",
  },
  {
    outputs: [{ name: "", internalType: "bool", type: "bool" }],
    inputs: [{ name: "", internalType: "address", type: "address" }],
    name: "isC50Started",
    stateMutability: "view",
    type: "function",
  },
  {
    outputs: [{ name: "", internalType: "bool", type: "bool" }],
    inputs: [{ name: "", internalType: "address", type: "address" }],
    name: "isRegistrationVirtualTokenClaimed",
    stateMutability: "view",
    type: "function",
  },
  {
    outputs: [{ name: "", internalType: "bool", type: "bool" }],
    inputs: [{ name: "", internalType: "address", type: "address" }],
    name: "isStandardRoiActive",
    stateMutability: "view",
    type: "function",
  },
  {
    outputs: [{ name: "", internalType: "bool", type: "bool" }],
    inputs: [{ name: "", internalType: "address", type: "address" }],
    name: "isSuperRoi",
    stateMutability: "view",
    type: "function",
  },
  {
    outputs: [{ name: "", internalType: "bool", type: "bool" }],
    inputs: [{ name: "", internalType: "address", type: "address" }],
    name: "isUserExist",
    stateMutability: "view",
    type: "function",
  },
  {
    outputs: [{ name: "", internalType: "uint256", type: "uint256" }],
    inputs: [{ name: "", internalType: "address", type: "address" }],
    name: "lastTimeClaim",
    stateMutability: "view",
    type: "function",
  },
  {
    outputs: [{ name: "", internalType: "address", type: "address" }],
    inputs: [],
    name: "operator",
    stateMutability: "view",
    type: "function",
  },
  {
    outputs: [{ name: "", internalType: "address", type: "address" }],
    inputs: [],
    name: "ownership",
    stateMutability: "view",
    type: "function",
  },
  {
    outputs: [],
    inputs: [{ name: "referal", internalType: "address", type: "address" }],
    name: "register",
    stateMutability: "payable",
    type: "function",
  },
  {
    outputs: [{ name: "", internalType: "uint256", type: "uint256" }],
    inputs: [{ name: "userAdr", internalType: "address", type: "address" }],
    name: "returnAvailableSplitWalletFund",
    stateMutability: "view",
    type: "function",
  },
  {
    outputs: [{ name: "", internalType: "string", type: "string" }],
    inputs: [{ name: "", internalType: "uint256", type: "uint256" }],
    name: "returnRank",
    stateMutability: "view",
    type: "function",
  },
  {
    outputs: [{ name: "", internalType: "uint256", type: "uint256" }],
    inputs: [{ name: "", internalType: "uint256", type: "uint256" }],
    name: "returnRankMaximumLimit",
    stateMutability: "view",
    type: "function",
  },
  {
    outputs: [{ name: "", internalType: "uint256", type: "uint256" }],
    inputs: [{ name: "", internalType: "uint256", type: "uint256" }],
    name: "returnRankPercent",
    stateMutability: "view",
    type: "function",
  },
  {
    outputs: [{ name: "", internalType: "uint256", type: "uint256" }],
    inputs: [{ name: "user", internalType: "address", type: "address" }],
    name: "returnUserQualificationLength",
    stateMutability: "view",
    type: "function",
  },
  {
    outputs: [
      { name: "", internalType: "uint256", type: "uint256" },
      { name: "", internalType: "uint256", type: "uint256" },
      { name: "", internalType: "uint256", type: "uint256" },
    ],
    inputs: [
      { name: "userAddress", internalType: "address", type: "address" },
      { name: "amount", internalType: "uint256", type: "uint256" },
      { name: "rankInUint", internalType: "uint256", type: "uint256" },
    ],
    name: "returnVirtualTokenAmountCanBeUsed",
    stateMutability: "view",
    type: "function",
  },
  {
    outputs: [{ name: "", internalType: "uint256", type: "uint256" }],
    inputs: [{ name: "", internalType: "address", type: "address" }],
    name: "totalClaimableIncome",
    stateMutability: "view",
    type: "function",
  },
  {
    outputs: [{ name: "", internalType: "uint256", type: "uint256" }],
    inputs: [{ name: "", internalType: "address", type: "address" }],
    name: "totalIncome",
    stateMutability: "view",
    type: "function",
  },
  {
    outputs: [{ name: "", internalType: "uint256", type: "uint256" }],
    inputs: [{ name: "", internalType: "address", type: "address" }],
    name: "totalWithdrawl",
    stateMutability: "view",
    type: "function",
  },
  {
    outputs: [],
    inputs: [
      { name: "user", internalType: "address", type: "address" },
      { name: "amount", internalType: "uint256", type: "uint256" },
    ],
    name: "updateIncome",
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    outputs: [],
    inputs: [
      { name: "_newOperator", internalType: "address", type: "address" },
    ],
    name: "updateOperator",
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    outputs: [],
    inputs: [
      { name: "downlineUser", internalType: "address", type: "address" },
      { name: "addressWhoTopup", internalType: "address", type: "address" },
      { name: "status", internalType: "bool", type: "bool" },
    ],
    name: "updateUserDownLine",
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    outputs: [],
    inputs: [
      { name: "users", internalType: "address[]", type: "address[]" },
      { name: "amounts", internalType: "uint256[]", type: "uint256[]" },
      { name: "incomeTypes", internalType: "string[]", type: "string[]" },
    ],
    name: "updateUserIncome",
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    outputs: [],
    inputs: [],
    name: "userClaimedRegistredToken",
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    outputs: [{ name: "", internalType: "bool", type: "bool" }],
    inputs: [
      { name: "", internalType: "address", type: "address" },
      { name: "", internalType: "address", type: "address" },
    ],
    name: "userDownline",
    stateMutability: "view",
    type: "function",
  },
  {
    outputs: [
      { name: "amount", internalType: "uint256", type: "uint256" },
      { name: "timeOfDeposit", internalType: "uint256", type: "uint256" },
      { name: "c50Active", internalType: "bool", type: "bool" },
      { name: "c50ActiveTime", internalType: "uint256", type: "uint256" },
      { name: "standardActive", internalType: "bool", type: "bool" },
      { name: "standardActiveTime", internalType: "uint256", type: "uint256" },
      { name: "lastClaimTime", internalType: "uint256", type: "uint256" },
    ],
    inputs: [
      { name: "", internalType: "address", type: "address" },
      { name: "", internalType: "uint256", type: "uint256" },
    ],
    name: "userQualificationDetail",
    stateMutability: "view",
    type: "function",
  },
  {
    outputs: [
      { name: "amount", internalType: "uint256", type: "uint256" },
      { name: "time", internalType: "uint256", type: "uint256" },
    ],
    inputs: [
      { name: "", internalType: "address", type: "address" },
      { name: "", internalType: "uint256", type: "uint256" },
    ],
    name: "userSplitPackage",
    stateMutability: "view",
    type: "function",
  },
  {
    outputs: [],
    inputs: [],
    name: "withdraw",
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    outputs: [],
    inputs: [],
    name: "withdrawBalance",
    stateMutability: "nonpayable",
    type: "function",
  },
];
export const base_url = window.location.origin;
